Revert "gts3l-common: boardconfig: Use Clang 11 for building kernel"
Specifying Clang version will cause an error like,

```
/media/additional-nvme/Developer/android/gts3l-lineage19/kernel/samsung/msm8996/scripts/mod/devic
etable-offsets.c:4:22: note: expanded from macro 'DEVID'
                     ^
/media/additional-nvme/Developer/android/gts3l-lineage19/kernel/samsung/msm8996/include/linux/kbu
ild.h:5:25: note: expanded from macro 'DEFINE'
        asm volatile("\n->" #sym " %0 " #val : : "i" (val))
                        ^
<inline asm>:2:1: note: instantiated into assembly here
->SIZE_usb_device_id $32 sizeof(struct usb_device_id)
^
/media/additional-nvme/Developer/android/gts3l-lineage19/kernel/samsung/msm8996/scripts/mod/devic
etable-offsets.c:11:2: error: unexpected token at start of statement
        DEVID_FIELD(usb_device_id, match_flags);
        ^
```

But without this option there is no problem with kernel building. So we
don't need to this for now.

And actually, this specifying selects Clang 12, not 11. The commit
message also was wrong.

This reverts commit 285a24f1c1859ab6bc3c8e474bda0b38f5980eb0.