gts3l-common: Adjust sensors groups. IPC_RTR: msm_ipc_router_bind
https://review.lineageos.org/c/LineageOS/android_device_lge_msm8996-common/+/272639

* IPC routing requests for sensors.qcom are getting rekt
  because root isn't in the allowed groups for sensors
* Fix this by adding system to the groups for sensors.qcom,
  which *is* one of the groups allowed to access sensors

E Sensors : sns_init_la.c(165):Error 5 initializing sns_reg_init
E [0:    sensors.qti: 1414] IPC_RTR: msm_ipc_router_bind: sensors.qti Do not have permissions
E libsensor1: wait_for_service: Service 0 is not available (8000 ms)
E qti_sensors_hal: sensor1 open failed!

With this commit, I can also write a SELinux policy.

allow sensors self:capability dac_override;