gts3l-common: Add net_raw to vendor.sensors.qti
No sensors show up until net_raw is added

E Sensors : sns_init_la.c(165):Error 5 initializing sns_reg_init
E [0:    sensors.qti: 1414] IPC_RTR: msm_ipc_router_bind: sensors.qti Do not have permissions
E libsensor1: wait_for_service: Service 0 is not available (8000 ms)
E qti_sensors_hal: sensor1 open failed!

https://review.lineageos.org/c/LineageOS/android_device_xiaomi_msm8996-common/+/339084